# Configuración del Agente Beca 18

agent:
  name: "Agente Beca 18"
  description: "Especialista en información sobre Beca 18 del gobierno peruano"

llm:
  model: "qwen2.5:7b"
  temperature: 0.3
  max_tokens: 1500
  context_window: 4096

embeddings:
  model: "paraphrase-multilingual-MiniLM-L12-v2"
  device: "cpu"  # cambiar a "cuda" si tienes GPU
  batch_size: 32

vectordb:
  path: "data/vectordb"  # ruta relativa a instances/beca18/
  collection: "beca18_docs"
  distance_metric: "cosine"

preprocessing:
  chunk_size: 800
  chunk_overlap: 100
  min_chunk_size: 100

prompts:
  system: "prompts/system_prompt.txt"
  template: "prompts/query_template.txt"

metadata:
  programa: "Beca 18"
  pais: "Perú"
  institucion: "Pronabec"

log_level: "INFO"